#═══════[ CORE CONFIG ]═══════✧#
SESSION_ID=''bbvbBWM-XMD;;;H4sIAAAAAAAAA5VUXZOiOBT9L3nVGkQ+FKu6ahARP7AVUUG35iFCgAgECBHEKf/7Fnb39Dzszva+JTfJPSfnnnt/ApLhEi1RA0Y/QU5xBRlql6zJERiB8TUIEAVd4EMGwQikr6bqZ3IYnhLncNYV13XmjUl0pAWew1878nmPgsq1KiN+AY8uyK/nBHt/SFgtpLVnRzOW6I0qT4LNpI/O3rIvW2kMp3fsReE02QjbVzJ8AY82I8QUk1DPI5QiCpMlajYQ06/Rl8fi9uQUpaD0RDJ2JRhZ3qG/VRM/W9tKXu0tcRGZSNvH6tfod4qpl9uihok6bUy3uDHN1SIjQ/VJ1AmTEgWn9bSnq7PsjX6JQ4L8uY8Iw6z5su7DCWXTwVwjl3W8Gzg3Pgz8NcPyyVokgxxmPXNRWuHyzqfh14jfuHVKx3YFhe1QzxyvE+RQqrf3pDbWCozN1cGE/Z7JTab734lv6IdX4v+ju6q/zmrR2i6rcqXWZ/+2dl28D+uwSmnG+ZPYtlUp4YeEeF+jrwbm7iyJXujXyj1Lxsd7GZ/TqZseiM3J0UrmvPlG5tHdnn/Sh+xK/8QSL6+JOyVjjg5Tg+RF7SQXRTtA1T5px5XJSwU0bX7mygKZvUbN3HoduppzWI2ZnUd0ytw+WsyDqORuCyfrqI0B9aFmvTx/FKNm7oMR/+gCikJcMgoZzsgzxktdAP3KRh5F7CkvoH2zczs7Isdup3M+9NNeYVz1wrTRyuddUdusz4cmNQ87O34BXZDTzENlifwZLllGmxUqSxiiEoz++tEFBN3YW+FaOIHvggDTku3JNU8y6H9U9eMQel52JcxuiKe1C0TBqPcZRoxhEpatjlcCqRfhCmkRZCUYBTAp0a8fIor899iv1+0rHzGIkxKMgLY2XXY6avoa+WSlG4aqh6oWquAT7aNsb7J4kb0bzop8ya1ux51K9zslK84cnZRcqFmGVaGsnmmEHpPs5R+StAOMmov8EjpJYvQcfVtoi+yCsnR3k0Ut2HbyNdOFFYIGRcVutmVHJY8Sa3OS6tOML6V5lK+ug5XATZShqFALbi87ZafWLy2ajyrsod/Baq04GXYyrun+3jf0DQ1v/K2y1sb12CyqqzwJsF3cF0nl9EjUmxy5S6lfFD8UeGV82Ozl2PB5155yHavmycBuevNsq74bKn06GftgBPqSOFAUeSBJgjASvpff6rYcMM+/EcRAFyTPW7zSVyRpyA/7PUmQ+iPhexv/aI3kfSThp2naxO02wOjZ4QS2cP8J9KZA66Peo/tbiveR8S9tN3bn+5gby4Vd3VeOXi95nYPLlJPrwUZU43FsCsVqXOdyfwHB4/GjC/IEsiCjKRgBSHyaYR90Ac2urTHnJMj+AKap+7mmvkmYwJKpn2bf4RSVDKY5GPEDcSAoPV4Zvt3a0CyfwTJqNTgMBsUePP4Gx2SJTToHAAA=
PREFIX="."
PUBLIC_MODE='yes'

#═══════[ OWNER DETAILS ]═══════✧#
OWNER_NAME="᚛Ibrahim adams᚜"
OWNER_NUMBER=""

#═══════[ BOT PROFILE ]═══════✧#
BOT_NAME="BWM-XMD"
BOT_IMAGE=""
STARTING_BOT_MESSAGE='yes'

#═══════[ PRESENCE & AUTOMATION ]═══════✧#
PRESENCE='2'
AUTO_READ="no"
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"

#═══════[ CHAT FEATURES ]═══════✧#
CHATBOT="no"
AUDIO_CHATBOT="no"

#═══════[ GROUP SECURITY ]═══════✧#
GROUPANTILINK_REMOVE="yes"
ANTIDELETE_SENT_INBOX="yes"
ANTIDELETE_RECOVER_CONVENTION="no"

#═══════[ MESSAGE HANDLING ]═══════✧#
STATUS_REACT_EMOJIS="🚀,🌎"
AUTO_REACT="no"
WELCOME_MESSAGE="no"
GOODBYE_MESSAGE="no"

#═══════[ HEROKU CONFIG ]═══════✧#
HEROKU_APP_NAME=
HEROKU_API_KEY=

#═══════[ AUTO REACTIONS ]═══════✧#
AUTO_REACT_STATUS="yes"
AUTO_REPLY_STATUS="no"
AUTO_REJECT_CALL="no"
AUTO_BIO="yes"
#════════════════════════════✧#
